// The sidebar follows the folder structure (docs/**, _category_.json).
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};
